module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🇿🇼', '🇺🇬', '🥶', '🔮'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/KQzM54TU1LmGwIGc2TcOGi?mode=wwt',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/x8tj8o.png',
    NEWSLETTER_JID: '120363404529319592@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Arslan-Mini-Bot ',
    OWNER_NAME: 'Ridz Coder',
    OWNER_NUMBER: '263714732501',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝙱𝚁𝙾𝚄𝙶𝙷𝚃 𝚃𝙾 𝚈𝙾𝚄 𝙱𝚈 𝙼𝙰𝚆𝚁𝙻𝙳 𝙼𝙳',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb73EYZFXUujAoHFor1i',
};